# Generated by Django 2.1.1 on 2018-09-04 17:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_catagory_image'),
        ('blog', '0002_move_m2m_field_to_post_and_update_tag'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='catagory',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='main.Catagory'),
        ),
    ]
